<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mayabank.processing</groupId>
  <artifactId>payment-processing-platform</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit.version>5.11.4</junit.version>
    <maven.compiler.version>3.13.0</maven.compiler.version>
    <maven.surefire.version>3.5.2</maven.surefire.version>
  </properties>
  <modules>
    <module>platform-sdk</module>
    <module>domain/card-domain</module>
    <module>services/authorization-service</module>
    <module>services/issuer-service</module>
    <module>services/scheme-router</module>
    <module>services/acquiring-service</module>
    <module>services/capture-service</module>
    <module>services/eventing-service</module>
    <module>services/ledger-service</module>
    <module>services/clearing-service</module>
    <module>services/settlement-service</module>
    <module>services/reconciliation-service</module>
    <module>services/dispute-service</module>
    <module>services/fraud-service</module>
    <module>simulators/cb-simulator</module>
    <module>simulators/visa-simulator</module>
    <module>simulators/mastercard-simulator</module>
    <module>tests/vertical-slice</module>
    <module>apps/payment-processing-api</module>
  </modules>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId><artifactId>junit-bom</artifactId><version>${junit.version}</version><type>pom</type><scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build><pluginManagement><plugins>
    <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>${maven.compiler.version}</version></plugin>
    <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-surefire-plugin</artifactId><version>${maven.surefire.version}</version></plugin>
  </plugins></pluginManagement></build>
</project>