<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
<parent><groupId>com.mayabank.processing</groupId><artifactId>payment-processing-platform</artifactId><version>0.1.0-SNAPSHOT</version><relativePath>../../pom.xml</relativePath></parent>
<artifactId>reconciliation-service</artifactId>
<dependencies>
 <dependency><groupId>com.mayabank.processing</groupId><artifactId>card-domain</artifactId><version>${project.version}</version></dependency>
 <dependency><groupId>com.mayabank.processing</groupId><artifactId>issuer-service</artifactId><version>${project.version}</version></dependency>
 <dependency><groupId>com.mayabank.processing</groupId><artifactId>settlement-service</artifactId><version>${project.version}</version></dependency>
 <dependency><groupId>com.mayabank.processing</groupId><artifactId>ledger-service</artifactId><version>${project.version}</version></dependency>
 <dependency><groupId>com.mayabank.processing</groupId><artifactId>authorization-service</artifactId><version>${project.version}</version></dependency>
 <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
</dependencies></project>