<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
<parent><groupId>com.mayabank.processing</groupId><artifactId>payment-processing-platform</artifactId><version>0.1.0-SNAPSHOT</version><relativePath>../../pom.xml</relativePath></parent>
<artifactId>cb-simulator</artifactId>
<dependencies>
 <dependency><groupId>com.mayabank.processing</groupId><artifactId>card-domain</artifactId><version>${project.version}</version></dependency>
</dependencies></project>